### ISSUE TITLE
PInvokeStackImbalance on soundio_connect()

### ISSUE THREAD

**Issue by 2steuer** [k5jae/SoundIOSharp#1]
Thank you very much for writing all that code. Sadly, I'm not able to get it working though :( Maybe you have some experience in the field and can help me.
When executing one of the sample projects, I always get a PInvokeStackImbalance exception, the german text reads:

> Der Assistent für verwaltetes Debugging ""PInvokeStackImbalance"" hat ein Problem in ""K:\Entwicklung\SoundIOSharp\SoundIOSharp\build\sio_sine.vshost.exe"" festgestellt.
> 
> Zusätzliche Informationen: Ein Aufruf an die PInvoke-Funktion "SoundIOSharp!SoundIOSharp.SoundIO::soundio_connect" hat das Gleichgewicht des Stapels gestört. Wahrscheinlich stimmt die verwaltete PInvoke-Signatur nicht mit der nicht verwalteten Zielsignatur überein. Überprüfen Sie, ob die Aufrufkonvention und die Parameter der PInvoke-Signatur mit der nicht verwalteten Zielsignatur übereinstimmen.

Roughly translated it says that there has been an imbalance in the stack due to the called function and that probably the signatures do not match.

Can you maybe help? As soon as I understood the problem I'd like to help working on this library since it is exactly what I need for a current project.

Thank you very much in advance,
Merlin

**Comment by 2steuer** [comment]
Some extra information: I'm running on Windows 7, .NET 4.6. Visual Studio 2015.

**Comment by k5jae** [comment]
I haven't had time to look at this yet. I'm hoping to soon.

**Comment by 2steuer** [comment]
Okay the thing is, that this error does not really matter for execution.
Nevertheless, now that everything is getting to work, I experience rather high CPU load caused by libsoundio. Did you also observe this? Would it be possible to get in touch with you on an e-mail or messenger do talk about this issue?

**Comment by k5jae** [comment]
Based on our conversation, this issue is no longer a problem.
